---
- name: lamp stack
  hosts: all
  become: yes
  tasks:
    - name: installing apache2
      apt:
       name: apache2
       state: present 
       update_cache: yes 
    - name: installing php 
      apt:
        name: php
        state: present
    - name: installing lib
      apt:
        name: libapache2-mod-php
        state: present
    - name: installing mysql 
      apt:
        name: php-mysql
        state: present
    - name: installing cli
      apt:
        name: php-cli
        state: present
    - name: copying a file
      copy: 
        src: info.php
        dest: /var/www/html/info.php
    - name: copying a file
      copy: 
        src: custom.html
        dest: /var/www/html/custom.html
