---
- name: incukding as playbook
  hosts: all
  become: yes
  tasks: 
   - name : adding a variable file 
     including_vars: var.yaml
   - name: importing a playbook 
     debug: 
       msg: play1 "{{ var1 }}"
     tags: yyy

   - name: including list of task
     include: including.yaml
   
     tags:
      - kkk
      - yyy
- name: including a playbook
  import_playbook: 1.yml
