---
- name: tomcat9 installation
  hosts: all
  become: yes
  tasks:
    - name: java installation
      apt:
       name: openjdk-11-jdk
       status: present
       update_cache: yes
    - name: tomcat9 installation
      apt:
       name: tomcat9 
       status: present
    - name: downloading a file
      get_url:
       url: wget https://referenceappkhaja.s3-us-west-2.amazonaws.com/gameoflife.war
       dest: /var/lib/tomcat8/webapps/gameoflife.war